- hosts: all 
  tasks:  
  - name: Install a list of packages
    yum:
     name:
      - apache2
      - git
      - wget
     state: latest

  - name: Start apache
    service:
      name: apache2
      state: started
      enabled: yes 